---
title: PROJETO FAPESP - Modelagem Computacional da Concentração Atmosférica de CO2 e CH4 no Brasil
  Central
author: "Pedro Henrique Marucio"
date: "2025-01-14"
output: html_document
---

## OBJETIVO

Analisar a variabilidade espaçotemporal das concentrações atmosféricas de CO2 e CH4 em áreas do Brasil Central, identificando fontes e possíveis sumidouros desses gases ao longo dos anos de 2015 a 2023, bem como suas relações com índices vegetativos e climáticos, por meio de dados de GOSAT, OCO-2 e Climate TRACE.

## ORGANIZAÇÃO DO DOCUMENTO Rmd GERADO

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	error = FALSE,
	message = FALSE,
	warning = FALSE
)

```

##### echo = T

*O código será mostrado no documento final.*

##### error = F, message = F, warning = F

*Erros, mensagens e avisos não aparecerão no documento final*

## FONTE DOS DADOS

### Relatórios Climate TRACE

Dados baixados para o Brasil, para todo o período (2015-2024), em CO2e 100 anos, no dia 15/01/2025.

Dados salvos na pasta data-raw ("climate-trace")

### Estação meteorológica

### Aquisição dos dados de focos de incêndio (NASA-FIRMS e INPE-BDQUEIMADAS)

#### NASA-FIRMS

Dados requisitados no link <https://firms.modaps.eosdis.nasa.gov/download/list.php>

Atributos dos dados solicitados: Country: "Brasil", Fire source: "MODIS", from "01/01/2015" to "01/01/2025", ".csv".

Passo a Passo para requisição dos dados de focos de incêndio para o Brasil, no período de 01/01/2015 a 01/01/2025:

1° Acesse: <https://firms.modaps.eosdis.nasa.gov>;

2° Selecione "ARCHIVE DOWNLOAD";

3° Selecione "Create New Request" (certifique-se que esta logado);

4° Selecione os atributos dos dados requeridos para download;

5° Aguarde e-mail com os dados solicitados (demora em torno de 6 horas);

Dados salvos na pasta data-raw ("firms_nasa").


#### BDQUEIMADAS

Dados requisitados no link <https://terrabrasilis.dpi.inpe.br/queimadas/bdqueimadas/#exportar-dados>

Atributos dos dados solicitados:

América do Sul, Brasil, Todos os estados, Satélite de referência (Aqua/MODIS), todos os biomas, período de 01/01/2015 a 01/01/2025 (período solicitado ano a ano, em razão do limite estabelecido pela plataforma), e-mail institucional, formato .csv. 

Dados salvos na pasta data-raw ("focos_deter_bdqueimadas").

#### DETER 

##### BR

Dados de focos de fogo do período de 08/2018 a 01/2025 para o Brasil adquiridos no link: <https://terrabrasilis.dpi.inpe.br/app/dashboard/fires/biomes/aggregated/#> Dados salvos em .csv na pasta "data-raw/focos_deter" como "br-18-24"

Satélite referência - AQUA/MODIS

##### Estados BRCentral

Dados de focos de fogo ativo para os estados do Brasil Central (Goiás, MT e MS) desde 1998  a 21/01/2025 no link:  <https://terrabrasilis.dpi.inpe.br/queimadas/situacao-atual/estatisticas/estatisticas_estados/>

Dados salvos em .csv na pasta "data-raw/focos_deter" como "brgo", "brmt" e "brms"

Satélite referência - AQUA/MODIS


## Produtos de mapeamento digital 

### Desmatamento - INPE

#### PRODES

Dados baixados para o Brasil, para todo o período (31/07/2000-30/07/2023), no dia 16/01/2025.

Mais informações no link: <https://terrabrasilis.dpi.inpe.br/geonetwork/srv/eng/catalog.search#/metadata/fe02f2bf-2cc0-49d5-ab72-a3954f997408>

Dados salvos na pasta "desmatamento_prodes/data-raw".
